### ISSUE TITLE
Port our QD MerlinEM support to rust

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM-rs#61]
To make `LiberTEM-live` more uniform, and to improve performance at the same time, our MerlinEM support should be ported to rust to work like our DECTRIS support.

## Tasks

- [x] Build the state machines (background receive thread and the foreground Python interface)
- [x] Make sure we can handle the QD quirks
  - [x] ~~Take care that we only open a single connection, as number of connections is limited~~ it's now less likely we hit issues with this, as the new version keeps the data connection open in the background while the `QdConnection` instance is still alive; only reconnects on errors
  - [x] Improved error handling - in case of an error, just continue to receive data from the detector system, if the error was not encountered in the main receive loop, and possibly just ignore said data (internal state: draining, which doesn't write to shm but only to a fixed buffer?). In active mode, stop the acquisition in case of exceptions?
- [x] Build parsers for the acquisition and frame headers
- [x] Extract some functionality (hopefully most of the "boring" state management that is very similar between the detectors) into a common crate, to make our detector support more uniform.
  - [x] Design towards having traits that are implemented for each detector, and having the high-level code generic over said traits

## Stretch goals

- [ ] Detector control library
  - [ ] low-level `get`/`set`/`cmd`. 
  - [ ] Higher-level: allow to set a desired state, have a `commit` function that sends over the `set` commands and afterwards `get`s them back and checks that the state has been reached (emit warnings for most things, but possibly errors for others - some attributes are supposed to change after setting, others not). Check for ordering constraints etc.
- [x] Port the decoders from our `numba` implementation to rust (can be done incrementally, as the data is put in an encoded state into the queue/shm, so the decoding can continue as it is done currently) - good reason to port is to get rid of jit compilation jitter on the first acquisition.
  - [ ] Implement support for layout options other than `2x2`
  - [x] Proper gap support when using raw format

@matbryan52 @uellue anything I'm missing here? Do you remember other quirks which we need to take care of?
